name: Cargo Build & Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (debug)
        run: cargo build --verbose
      # - name: Run tests
      #   run: cargo test --verbose
      - name: Upload (debug)
        uses: actions/upload-artifact@v4
        with:
          name: gad-debug
          path: target/debug/gad
      - name: Build (release)
        run: cargo build --verbose --release
      - name: Upload (release)
        uses: actions/upload-artifact@v4
        with:
          name: gad-release
          path: target/release/gad
